baseURL: https://ignimi.vercel.app # ç»‘å®šçš„åŸŸå
title: ignimi posts
theme: PaperMod # ä¸»é¢˜åç§°ï¼Œå’Œthemesæ–‡ä»¶å¤¹ä¸‹çš„ä¸€è‡´
languageCode: zh

enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true

minify:
    disableXML: true

permalinks:
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: zh # æœ€é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€é¡µé¢
defaultContentLanguageInSubdir: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

languages:
    zh:
      languageName: "Chinese"
      weight: 1

      menu:
        main:
          - identifier: search
            name: ğŸ” Search
            url: search
            weight: 1
          - identifier: posts
            name: ğŸ“‘ Posts
            url: /posts
            weight: 2
          - identifier: archives
            name: ğŸ“† Timeline
            url: /archives
            weight: 3
          - identifier: categories
            name: ğŸ§© Category
            url: categories
            weight: 4
          - identifier: tags
            name: ğŸ“Œ Tags
            url: /tags
            weight: 5
          - identifier: about
            name: ğŸ™‹ğŸ»â€â™‚ï¸ About
            url: /about
            weight: 6

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production
  author: ignimi
  defaultTheme: auto
  DateFormat: "2006-01-02"
  ShowToc: true # æ˜¾ç¤ºç›®å½•
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•

  socialIcons:
    - name: github
      url: "https://github.com/ignimi"

  assets:
    favicon: /img/favicon.ico
    favicon16x16: /img/favicon.ico
    favicon32x32: /img/favicon.ico
